# Makefile frontend for scikit-build-core project
# Generated by buildgen for: pysunvox
#
# This Makefile wraps common build commands for convenience.
# The actual build is handled by scikit-build-core via pyproject.toml

.PHONY: all sync build rebuild test clean distclean wheel sdist check publish publish-test help

# Detect OS
UNAME_S := $(shell uname -s)

# Default target
all: build

# Sync environment (initial setup, installs dependencies + package)
sync:
	uv sync

# Build/rebuild the extension after code changes
build:
	uv sync --reinstall-package pysunvox

# Alias for build
rebuild: build

# Run tests
test:
	uv run pytest tests/ -v

# Build wheel with platform-specific library bundling
wheel:
	uv build --wheel
ifeq ($(UNAME_S),Darwin)
	uv run delocate-wheel -v dist/*.whl
endif
ifeq ($(UNAME_S),Linux)
	uv run auditwheel repair dist/*.whl -w dist/
	@rm -f dist/*-linux_*.whl
endif
ifeq ($(OS),Windows_NT)
	uv run delvewheel repair dist/*.whl -w dist/
endif

# Build source distribution
sdist:
	uv build --sdist

# Check distribution with twine
check:
	uv run twine check dist/*

# Publish to PyPI
publish: check
	uv run twine upload dist/*

# Publish to TestPyPI
publish-test: check
	uv run twine upload --repository testpypi dist/*

# Clean build artifacts
clean:
	@rm -rf build/
	@rm -rf dist/
	@rm -rf *.egg-info/
	@rm -rf src/*.egg-info/
	@rm -rf .pytest_cache/
	@find . -name "*.so" -delete
	@find . -name "*.pyd" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# Clean everything including CMake cache
distclean: clean
	@rm -rf CMakeCache.txt CMakeFiles/

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - Build/rebuild the extension (default)"
	@echo "  sync         - Sync environment (initial setup)"
	@echo "  build        - Rebuild extension after code changes"
	@echo "  rebuild      - Alias for build"
	@echo "  test         - Run tests"
	@echo "  wheel        - Build wheel with bundled libraries"
	@echo "  sdist        - Build source distribution"
	@echo "  check        - Check distribution with twine"
	@echo "  publish      - Publish to PyPI (runs check first)"
	@echo "  publish-test - Publish to TestPyPI (runs check first)"
	@echo "  clean        - Remove build artifacts"
	@echo "  distclean    - Remove all generated files"
	@echo "  help         - Show this help message"
