# Makefile frontend for scikit-build-core project
# Generated by buildgen for: pysunvox
#
# This Makefile wraps common build commands for convenience.
# The actual build is handled by scikit-build-core via pyproject.toml

.PHONY: all sync build rebuild test clean distclean wheel sdist check publish publish-test\
		help build-wheel build-wheels fix-wheels check-wheels release

# Detect OS
UNAME_S := $(shell uname -s)

# Default target
all: build

# Sync environment (initial setup, installs dependencies + package)
sync:
	@uv sync

# Build/rebuild the extension after code changes
build:
	@uv sync --reinstall-package pysunvox

# Alias for build
rebuild: build

# Run tests
test:
	@uv run pytest tests/ -v

# Build wheel with platform-specific library bundling
build-wheel:
	@uv build --wheel

# Build wheels with platform-specific library bundling
build-wheels:
	@uv build --wheel --python 3.10
	@uv build --wheel --python 3.11
	@uv build --wheel --python 3.12
	@uv build --wheel --python 3.13
	@uv build --wheel --python 3.14

# fix rpath issues if any
fix-wheels:
ifeq ($(UNAME_S),Darwin)
	@uv run delocate-wheel -v dist/*.whl
endif
ifeq ($(UNAME_S),Linux)
	@uv run auditwheel repair dist/*.whl -w dist/
	@rm -f dist/*-linux_*.whl
endif
ifeq ($(OS),Windows_NT)
	@uv run delvewheel repair dist/*.whl -w dist/ --add-path sunvox_lib/windows/lib_x86_64
endif

# Make a platform-specific wheel
wheel: build-wheel fix-wheels check

# Make a platform-specific set of wheels
release: build-wheels fix-wheels check

# Build source distribution
sdist:
	@uv build --sdist

# Check distribution with twine
check-wheels:
	@uv run twine check dist/*
check: check-wheels

# Publish to PyPI
publish: check
	@uv run twine upload dist/*

# Publish to TestPyPI
publish-test: check
	@uv run twine upload --repository testpypi dist/*

# Clean build artifacts
clean:
	@rm -rf build/
	@rm -rf dist/
	@rm -rf *.egg-info/
	@rm -rf src/*.egg-info/
	@rm -rf .pytest_cache/
	@find . -name "*.pyd" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# Clean everything including CMake cache
distclean: clean
	@rm -rf CMakeCache.txt CMakeFiles/

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - Build/rebuild the extension (default)"
	@echo "  sync         - Sync environment (initial setup)"
	@echo "  build        - Rebuild extension after code changes"
	@echo "  rebuild      - Alias for build"
	@echo "  test         - Run tests"
	@echo "  wheel        - Build wheel with bundled libraries"
	@echo "  sdist        - Build source distribution"
	@echo "  check        - Check distribution with twine"
	@echo "  publish      - Publish to PyPI (runs check first)"
	@echo "  publish-test - Publish to TestPyPI (runs check first)"
	@echo "  clean        - Remove build artifacts"
	@echo "  distclean    - Remove all generated files"
	@echo "  help         - Show this help message"
